name: Merge

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14.15.x'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/yarn
        key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-
    - run: yarn --frozen-lockfile
    - run: yarn build:affected --base=origin/main~1 --head=HEAD
    - run: yarn release:affected --base=origin/main~1 --head=HEAD
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
