name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.x'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
          key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - run: yarn --frozen-lockfile
      - run: yarn lint:affected --maxWarnings 0 --base=origin/master --head=HEAD
      - run: yarn format:check --base=origin/master --head=HEAD
      - run: yarn build:affected --base=origin/master --head=HEAD

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.x'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
          key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - run: yarn --frozen-lockfile
      - run: yarn test:affected --base=origin/master --head=HEAD
